### ISSUE TITLE
Switch Update 5.0.0 messed up grip colors

### ISSUE THREAD

**Issue by vagrantvalmar** [CTCaer/jc_toolkit#16] opened 2018-03-13 03:39 UTC
Using the Xenoblade Pro controller as an example, I always get white/colorless grips when syncing with the console, even after restoring the SPI

**Comment by CTCaer** [comment] 2018-03-13 08:01
I knew that things will change with switch 5.
The problem is that I can't update yet to test these.

What were the original colors?
0x323232 and 0xFFFFFF?
0x313232 and 0xFFFFFF?
sth else?

Can you try some color combinations?
Also try for body and buttons to write colors on this format: `#RGBRGB` instead of `#RRGGBB`.
Maybe we can find the algorithm used.

**Comment by CTCaer** [comment] 2018-03-13 11:29
OK some more info.
I saw the normal pro how it looks.
Dark body, grey grips white buttons. 
I assume that buttons remain the same.

So probably the body color does the job. Otherwise it checks something new also.

Lastly try to do a full restore and a color restore and check which one works for you

**Comment by vagrantvalmar** [comment] 2018-03-13 11:35
Ok, so somehow I fixed this, here's what I did:  I did a full restore and color restore and at first it didn't seem to work, but then I manually changed the controller buttons to white and voilà! It showed the correct grip color and everything.

Hope this helps and thanks for your support!

**Comment by CTCaer** [comment] 2018-03-13 12:31
@vagrantvalmar 
Hmm strange.
Anyway, please try some color combinations if you don't mind.
Specifically body color to `#313232`

**Comment by vagrantvalmar** [comment] 2018-03-13 19:20
If I use body color #313232 (and white buttons) it gives me the Splatoon grips.

**Comment by CTCaer** [comment] 2018-03-13 21:15
And #323132 is Xenoblade.

So, if you put #313232 and custom buttons, you get dark grey body + white grips + custom color buttons or white buttons?

Additionally, if you put both to custom colors you get them but with white grips?

**Comment by vagrantvalmar** [comment] 2018-03-14 01:14
Weird, I made a 3rd edit that didn't get posted.
Yes I get dark grey body + white grips + custom buttons.

And also, yes, both customs work but with white grips as well.

Pretty much any non-official combination gives me white grips.


I'll give that a try right now

**Comment by CTCaer** [comment] 2018-03-14 01:32
Thank you for testing.

If you don't mind, can you test the following Body colors with white buttons:
#323231
#313131, #323131, #313132 (Check only one)
#323212, #321232, #123232 (Check only one)
#113232, #321132, #323211 (Check only one)
#111111

I'm trying to find if there's a pattern and also other grips in v5.0.0

**Comment by vagrantvalmar** [comment] 2018-03-14 02:31
323231 - white grips
313131 - white grips
321232 - white grips
323211 - white grips
111111 - white grips

**Comment by CTCaer** [comment] 2018-03-14 02:58
Lol! I really can't believe they implemented it like this..

Why the else case had to be white grips and not the body color...

They took a crap on the cosmetic modders

I'll implement it in someway to the toolkit

**Comment by CTCaer** [comment] 2018-03-14 08:09
Hello again, I have some news:
It seems that black buttons let you choose controller grip color:
![](https://uploads.tapatalk-cdn.com/20180314/b748935785b12f98396f2d0bc7dd1518.jpg)

Can you try: 
- `#000000` `#000000`
- `#FF3C28` `#000000`

**Comment by CTCaer** [comment] 2018-03-19 13:58
This is fixed internally with the following:

- If Buttons are white:
normal pro or splatoon or xeno or white (if body is custom)
- If Buttons are custom:
white grips
- If Buttons are black and body is black:
black grips

But it's still how it really works is unknown.

**Comment by CTCaer** [comment] 2018-03-29 00:07
Published

**Closed by CTCaer** 2018-03-29 00:07 UTC
Labels: bug, help wanted

**Comment by ethayer** [comment] 2018-10-02 19:21
Seems like Nintendo implemented grip colors in a weird way.  I wouldn't call it "white" when the controller defaults to something else, seems like you need to use specific colors for the UI to show the custom grip color (Like Splatoon or Xenoblade, or the DEFAULT which shows a slightly lighter black grip)

I'd say that for custom colors, Nintendo forces the grips to be _transparent_.  I can set the grips to a custom color and while disconnecting and re-connecting to the switch, I can sometimes get it to flash the set color on the UI for a fraction of a second before it turns the grip icon transparent.

So that makes me believe the controller stores these colors correctly, but Nintendo is turning the style of the grip to transparent when certain conditions aren't met.
