### ISSUE TITLE
Running on Parallels

### ISSUE THREAD

**Issue by XeroShi** [CTCaer/jc_toolkit#21] opened 2018-05-12 21:53 UTC
The joycon connected but the tool kit did not even recognize the the right joycon that was connected.

**Comment by UlyssesWu** [comment] 2018-05-13 07:22
~~Duplicate of ♯5~~

I misunderstood your issue. Sorry!

**Comment by XeroShi** [comment] 2018-05-15 01:49
>Currently it does not support dual joy-con.
Add icon-based selector.
Add dual joy-con button test
Add usb support?
I'm only using One joycon. I'm Using VMware though.

**Comment by CTCaer** [comment] 2018-05-15 08:19
Try the -f command line option.
The problem probably originates from VMware, but to make sure, check that you have the microsoft bluetooth stack on the guest OS

**Closed as completed** 2018-12-27 09:34 UTC
